//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laiq {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Laiq.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About LaiQ.
        /// </summary>
        public static string AboutLaiq {
            get {
                return ResourceManager.GetString("AboutLaiq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br /&gt;
        ///            &lt;h2 class=&quot;font-weight-normal&quot;&gt;LaiQ&lt;/h2&gt;
        ///            &lt;br /&gt;
        ///            &lt;h5 class=&quot;font-italic font-weight-normal&quot;&gt;&apos;Bring energy to our team&apos;&lt;/h5&gt;
        ///            &lt;br /&gt;
        ///            &lt;p&gt;
        ///LaiQ, which stands for ‘Looking for Adept Intelligence Quotient’, is a program initiated by Da Afghanistan Breshna Sherkat (DABS) to encourage and facilitate employment opportunities for cutting-edge talents and well-educated Afghan nationals to join DABS. 
        ///            &lt;/p&gt;
        ///            &lt;p&gt;
        ///Through thi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutLaiqText {
            get {
                return ResourceManager.GetString("AboutLaiqText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievement.
        /// </summary>
        public static string Achievement {
            get {
                return ResourceManager.GetString("Achievement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Education.
        /// </summary>
        public static string AddEdu {
            get {
                return ResourceManager.GetString("AddEdu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Experience.
        /// </summary>
        public static string AddExp {
            get {
                return ResourceManager.GetString("AddExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Language.
        /// </summary>
        public static string AddLanguage {
            get {
                return ResourceManager.GetString("AddLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add more.
        /// </summary>
        public static string addmore {
            get {
                return ResourceManager.GetString("addmore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add References.
        /// </summary>
        public static string AddReferences {
            get {
                return ResourceManager.GetString("AddReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Skills.
        /// </summary>
        public static string AddSkill {
            get {
                return ResourceManager.GetString("AddSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree to save my application  in DABS database for.
        /// </summary>
        public static string AgreeSave {
            get {
                return ResourceManager.GetString("AgreeSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Applicant.
        /// </summary>
        public static string Applicant {
            get {
                return ResourceManager.GetString("Applicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied Jobs.
        /// </summary>
        public static string AppliedJobs {
            get {
                return ResourceManager.GetString("AppliedJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Now.
        /// </summary>
        public static string ApplyNow {
            get {
                return ResourceManager.GetString("ApplyNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you &lt;b&gt;determined&lt;/b&gt; to reflect on your competencies?.
        /// </summary>
        public static string Areyoudetermined {
            get {
                return ResourceManager.GetString("Areyoudetermined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Bachelor&apos;s Degree Information.
        /// </summary>
        public static string Bachelor {
            get {
                return ResourceManager.GetString("Bachelor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bachelor&apos;s Degree.
        /// </summary>
        public static string BachelorDegree {
            get {
                return ResourceManager.GetString("BachelorDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        public static string Basic {
            get {
                return ResourceManager.GetString("Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span&gt;Apply Now&lt;/span&gt; and add &lt;b&gt;energy&lt;/b&gt; to our team.
        /// </summary>
        public static string bringenergy {
            get {
                return ResourceManager.GetString("bringenergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill out the below form and click on the submit button to register your profile with us!.
        /// </summary>
        public static string BuildProfile {
            get {
                return ResourceManager.GetString("BuildProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build your profile.
        /// </summary>
        public static string BuildYourProfile {
            get {
                return ResourceManager.GetString("BuildYourProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can DABS share your application with other government organizations and stated own company?.
        /// </summary>
        public static string CanDABSShare {
            get {
                return ResourceManager.GetString("CanDABSShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can DABS share your picture on social media?.
        /// </summary>
        public static string CanDABSSharePic {
            get {
                return ResourceManager.GetString("CanDABSSharePic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can DABS share your video message on social media?.
        /// </summary>
        public static string CanDABSShareVideo {
            get {
                return ResourceManager.GetString("CanDABSShareVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Compatriots,.
        /// </summary>
        public static string CEO1 {
            get {
                return ResourceManager.GetString("CEO1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am entirely privileged to affirm that Da Afghanistan Breshna Sherkat (DABS) has been tremendously committed to reach the organizational vision, and transform the status quo of DABS to achieve greater success. At DABS, we, as robust teams, are striving persistently to provide rooms for educated and talented Afghan youth through a merit-based program called LaiQ, so they would render services to the country after joining DABS..
        /// </summary>
        public static string CEO2 {
            get {
                return ResourceManager.GetString("CEO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DABS is expected to take more than 10,000 applications into consideration through this program to facilitate employment opportunities for thousands of educated youth who are equipped with up-to-dated and ground-breaking ideas, knowledge and competencies required for the 21st century to turn DABS into one of the leading and exceptional power-utility corporations in the region aimed at providing safe and reliable power with reasonable rates to people to facilitate national economic growth..
        /// </summary>
        public static string CEO3 {
            get {
                return ResourceManager.GetString("CEO3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finally, yet importantly, I want to emphasize that we’re strongly hopeful to make big changes through this program within DABS by transforming this entity into one of the dynamic institutions in Afghanistan – fully dedicated to serve the nation and country..
        /// </summary>
        public static string CEO4 {
            get {
                return ResourceManager.GetString("CEO4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finally, yet importantly, I want to emphasize that we’re strongly hopeful to make big changes through the LaIQ program within DABS, transforming this entity into one of the dynamic institutions in Afghanistan – fully dedicated to serve the nation and country..
        /// </summary>
        public static string CEO5 {
            get {
                return ResourceManager.GetString("CEO5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sincerly,.
        /// </summary>
        public static string CEO6 {
            get {
                return ResourceManager.GetString("CEO6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ahmad Daud Noorzai.
        /// </summary>
        public static string CEO7 {
            get {
                return ResourceManager.GetString("CEO7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chief Executive Officer.
        /// </summary>
        public static string CEO8 {
            get {
                return ResourceManager.GetString("CEO8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEO&apos;s Message.
        /// </summary>
        public static string CEOMSG {
            get {
                return ResourceManager.GetString("CEOMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br /&gt;
        ///            &lt;h2 class=&quot;font-weight-normal&quot;&gt;&lt;span style=&quot;text-decoration:underline&quot; class=&quot;Underline&quot;&gt;CEO&apos;&lt;/span&gt;s Message&lt;/h2&gt;
        ///            &lt;br /&gt;
        ///            &lt;h5 class=&quot;font-italic font-weight-normal&quot;&gt;&apos;To improve it to chang; to be perfect is to change often&apos;&lt;/h5&gt;
        ///            &lt;br /&gt;
        ///            &lt;p&gt;
        ///                Considering the above quotes, I am strongly hopeful to make big changes through implementing
        ///                LAIQ program within DABS.
        ///            &lt;/p&gt;
        ///            &lt;br /&gt;
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CEOText {
            get {
                return ResourceManager.GetString("CEOText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certifications.
        /// </summary>
        public static string Certifications {
            get {
                return ResourceManager.GetString("Certifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Form.
        /// </summary>
        public static string CloseForm {
            get {
                return ResourceManager.GetString("CloseForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional comments and feedback: (Please add your comments,suggestions and ideas).
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application with complete documents will be preferred..
        /// </summary>
        public static string CompleteDoc {
            get {
                return ResourceManager.GetString("CompleteDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Profile.
        /// </summary>
        public static string CompleteProfile {
            get {
                return ResourceManager.GetString("CompleteProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete your Profile.
        /// </summary>
        public static string compprof {
            get {
                return ResourceManager.GetString("compprof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer Application.
        /// </summary>
        public static string computerapplication {
            get {
                return ResourceManager.GetString("computerapplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your computer skills.
        /// </summary>
        public static string computerskilmessage {
            get {
                return ResourceManager.GetString("computerskilmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email and Verify your email address.
        /// </summary>
        public static string ConfirmationMessage {
            get {
                return ResourceManager.GetString("ConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Confirmation Please Enter Your NID Number.
        /// </summary>
        public static string ConfirmTitle {
            get {
                return ResourceManager.GetString("ConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string Contactus {
            get {
                return ResourceManager.GetString("Contactus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Address.
        /// </summary>
        public static string CurrentAddress {
            get {
                return ResourceManager.GetString("CurrentAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV.
        /// </summary>
        public static string cv {
            get {
                return ResourceManager.GetString("cv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUMAN RESOUCES DIRECOTRATE.
        /// </summary>
        public static string DABHR {
            get {
                return ResourceManager.GetString("DABHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DA AFGHANISTAN BRESHNA SHERKAT.
        /// </summary>
        public static string DABS {
            get {
                return ResourceManager.GetString("DABS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DABS Facebook.
        /// </summary>
        public static string DABSFacebook {
            get {
                return ResourceManager.GetString("DABSFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DABS Twitter.
        /// </summary>
        public static string DABSTwitter {
            get {
                return ResourceManager.GetString("DABSTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dari.
        /// </summary>
        public static string Dari {
            get {
                return ResourceManager.GetString("Dari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        public static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string DOB {
            get {
                return ResourceManager.GetString("DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type.
        /// </summary>
        public static string docType {
            get {
                return ResourceManager.GetString("docType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documnet.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have work experience?.
        /// </summary>
        public static string doyouhaveworkexp {
            get {
                return ResourceManager.GetString("doyouhaveworkexp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to upload your documents?.
        /// </summary>
        public static string doyouupload {
            get {
                return ResourceManager.GetString("doyouupload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to &lt;b&gt;serve your country &lt;/b&gt; ?.
        /// </summary>
        public static string doyouwant {
            get {
                return ResourceManager.GetString("doyouwant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string EducationField {
            get {
                return ResourceManager.GetString("EducationField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s the highest level of your education?.
        /// </summary>
        public static string EducationLevel {
            get {
                return ResourceManager.GetString("EducationLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education is Required.
        /// </summary>
        public static string EduRefMessage {
            get {
                return ResourceManager.GetString("EduRefMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many employees are working or worked under your supervision?.
        /// </summary>
        public static string empundersupervision {
            get {
                return ResourceManager.GetString("empundersupervision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date Shamse/Meladi.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter your registration which you have recived in LaiQ confrimation email.
        /// </summary>
        public static string enteryourid {
            get {
                return ResourceManager.GetString("enteryourid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excellent.
        /// </summary>
        public static string Excellent {
            get {
                return ResourceManager.GetString("Excellent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much salary in AFN do you expect?.
        /// </summary>
        public static string expectfromdabs {
            get {
                return ResourceManager.GetString("expectfromdabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience.
        /// </summary>
        public static string Experience {
            get {
                return ResourceManager.GetString("Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your experience level?.
        /// </summary>
        public static string explevel {
            get {
                return ResourceManager.GetString("explevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Uploaded Successfully.
        /// </summary>
        public static string FileUploaded {
            get {
                return ResourceManager.GetString("FileUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father Name.
        /// </summary>
        public static string FName {
            get {
                return ResourceManager.GetString("FName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forever.
        /// </summary>
        public static string Forever {
            get {
                return ResourceManager.GetString("Forever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Informaion.
        /// </summary>
        public static string GeneralInformation {
            get {
                return ResourceManager.GetString("GeneralInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Father Name.
        /// </summary>
        public static string GFName {
            get {
                return ResourceManager.GetString("GFName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        public static string Good {
            get {
                return ResourceManager.GetString("Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graduation Year.
        /// </summary>
        public static string GraduationYear {
            get {
                return ResourceManager.GetString("GraduationYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many years of experience do you have?.
        /// </summary>
        public static string howmanyexp {
            get {
                return ResourceManager.GetString("howmanyexp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR.
        /// </summary>
        public static string HR {
            get {
                return ResourceManager.GetString("HR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear Applicants,.
        /// </summary>
        public static string HR1 {
            get {
                return ResourceManager.GetString("HR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LaiQ Program is a talent acquisition initiative to attract, select and orient competent talents to promote organizational efficiency and gain competitive advantage. DABS HR Directorate is committed to filling the in-demand skills gap aimed at fostering the growth and development of DABS by ensuring transparency and equality..
        /// </summary>
        public static string HR2 {
            get {
                return ResourceManager.GetString("HR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We welcome and appreciate your innovative and brilliant ideas through any possible platforms..
        /// </summary>
        public static string HR3 {
            get {
                return ResourceManager.GetString("HR3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please do not hesitate to contact me through qudrat.k@dabs.af..
        /// </summary>
        public static string HR4 {
            get {
                return ResourceManager.GetString("HR4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regards,.
        /// </summary>
        public static string HR5 {
            get {
                return ResourceManager.GetString("HR5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qudratullah Karimi.
        /// </summary>
        public static string HR6 {
            get {
                return ResourceManager.GetString("HR6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR Director.
        /// </summary>
        public static string HR7 {
            get {
                return ResourceManager.GetString("HR7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if yes, Then register yourself.
        /// </summary>
        public static string ifyes {
            get {
                return ResourceManager.GetString("ifyes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are acquainted with other languages, click on the add more button.
        /// </summary>
        public static string ifyoumorelang {
            get {
                return ResourceManager.GetString("ifyoumorelang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is time to bring &lt;b&gt;light&lt;/b&gt; to entire homes in Afghanistan.
        /// </summary>
        public static string Itistimetobring {
            get {
                return ResourceManager.GetString("Itistimetobring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Detail.
        /// </summary>
        public static string JobDetail {
            get {
                return ResourceManager.GetString("JobDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job List.
        /// </summary>
        public static string JobList {
            get {
                return ResourceManager.GetString("JobList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title /Organizaion.
        /// </summary>
        public static string JOBOrgan {
            get {
                return ResourceManager.GetString("JOBOrgan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs.
        /// </summary>
        public static string Jobs {
            get {
                return ResourceManager.GetString("Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Search.
        /// </summary>
        public static string JobSearch {
            get {
                return ResourceManager.GetString("JobSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        public static string Jobtitle {
            get {
                return ResourceManager.GetString("Jobtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LaiQ.
        /// </summary>
        public static string LaiQ {
            get {
                return ResourceManager.GetString("LaiQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you insert wrong information in national or international languages you will be disqualified from the process..
        /// </summary>
        public static string langnote {
            get {
                return ResourceManager.GetString("langnote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Skills.
        /// </summary>
        public static string langSkill {
            get {
                return ResourceManager.GetString("langSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Proficiency.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What was your last salary in AFN?.
        /// </summary>
        public static string lastsalaryinAFN {
            get {
                return ResourceManager.GetString("lastsalaryinAFN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LName {
            get {
                return ResourceManager.GetString("LName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to DABS HRIS.
        /// </summary>
        public static string LoginWelcomeMessage {
            get {
                return ResourceManager.GetString("LoginWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you looking for a &lt;b&gt;better oppurtunity &lt;/b&gt;  in a dynamic organization ?.
        /// </summary>
        public static string lookingfor {
            get {
                return ResourceManager.GetString("lookingfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Master&apos;s Degree Information.
        /// </summary>
        public static string Master {
            get {
                return ResourceManager.GetString("Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master&apos;s  Degree.
        /// </summary>
        public static string MasterDegree {
            get {
                return ResourceManager.GetString("MasterDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WhatsApp Number.
        /// </summary>
        public static string Mobile1 {
            get {
                return ResourceManager.GetString("Mobile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Month.
        /// </summary>
        public static string Month1 {
            get {
                return ResourceManager.GetString("Month1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 Months.
        /// </summary>
        public static string Month6 {
            get {
                return ResourceManager.GetString("Month6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have more than one degree, click on add more button.
        /// </summary>
        public static string moredegree {
            get {
                return ResourceManager.GetString("moredegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have more skills, click on the add more button.
        /// </summary>
        public static string moreskill {
            get {
                return ResourceManager.GetString("moreskill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your NID Number.
        /// </summary>
        public static string NIDFill {
            get {
                return ResourceManager.GetString("NIDFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Not Found Please Accuritly enter Your NID Number.
        /// </summary>
        public static string NIDNotFoundMessage {
            get {
                return ResourceManager.GetString("NIDNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NID Number.
        /// </summary>
        public static string NIDNumber {
            get {
                return ResourceManager.GetString("NIDNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Photo.
        /// </summary>
        public static string Nofile {
            get {
                return ResourceManager.GetString("Nofile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Noo {
            get {
                return ResourceManager.GetString("Noo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note1 {
            get {
                return ResourceManager.GetString("Note1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have applied previously to a position in DABS through this online job portal, please just enter your NID Number and submit the application otherwise click cancel button and fill the form.
        /// </summary>
        public static string NoteBody {
            get {
                return ResourceManager.GetString("NoteBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application not found.
        /// </summary>
        public static string notfound {
            get {
                return ResourceManager.GetString("notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pashto.
        /// </summary>
        public static string Pashto {
            get {
                return ResourceManager.GetString("Pashto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanent Address.
        /// </summary>
        public static string PermanentAddress {
            get {
                return ResourceManager.GetString("PermanentAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your PhD Degree Information.
        /// </summary>
        public static string PhD {
            get {
                return ResourceManager.GetString("PhD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select photo not exceeding one MB.
        /// </summary>
        public static string PhotoText {
            get {
                return ResourceManager.GetString("PhotoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application with positive responses will be preferred..
        /// </summary>
        public static string PositiveResponse {
            get {
                return ResourceManager.GetString("PositiveResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualification.
        /// </summary>
        public static string Qualification {
            get {
                return ResourceManager.GetString("Qualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field of Study.
        /// </summary>
        public static string QualificationArea {
            get {
                return ResourceManager.GetString("QualificationArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        public static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading.
        /// </summary>
        public static string Reading {
            get {
                return ResourceManager.GetString("Reading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        public static string Record {
            get {
                return ResourceManager.GetString("Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum 3 References is Required.
        /// </summary>
        public static string RefReqMessage {
            get {
                return ResourceManager.GetString("RefReqMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Saved, Please insert next or click Cancel.
        /// </summary>
        public static string RefSuccessMessage {
            get {
                return ResourceManager.GetString("RefSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Registration Number is:.
        /// </summary>
        public static string RegistraionNo {
            get {
                return ResourceManager.GetString("RegistraionNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration in DABS HR .
        /// </summary>
        public static string RegistrationTitle {
            get {
                return ResourceManager.GetString("RegistrationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum 3 References is Required.
        /// </summary>
        public static string RegMessage {
            get {
                return ResourceManager.GetString("RegMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is Required.
        /// </summary>
        public static string RequiredEmail {
            get {
                return ResourceManager.GetString("RequiredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father Name is Required.
        /// </summary>
        public static string RequiredFName {
            get {
                return ResourceManager.GetString("RequiredFName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Father Name is Required.
        /// </summary>
        public static string RequiredGFName {
            get {
                return ResourceManager.GetString("RequiredGFName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name is Required.
        /// </summary>
        public static string RequiredLName {
            get {
                return ResourceManager.GetString("RequiredLName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is Required.
        /// </summary>
        public static string RequiredName {
            get {
                return ResourceManager.GetString("RequiredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NID No is Required.
        /// </summary>
        public static string RequiredNID {
            get {
                return ResourceManager.GetString("RequiredNID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Retyp Email Address.
        /// </summary>
        public static string RetypeEmail {
            get {
                return ResourceManager.GetString("RetypeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Retype Password.
        /// </summary>
        public static string RetypePassword {
            get {
                return ResourceManager.GetString("RetypePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LaiQ, All rights reserved.
        /// </summary>
        public static string RightReserved {
            get {
                return ResourceManager.GetString("RightReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        public static string Salary {
            get {
                return ResourceManager.GetString("Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Continue.
        /// </summary>
        public static string saveandcontinue {
            get {
                return ResourceManager.GetString("saveandcontinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Sucessfully.
        /// </summary>
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Country.
        /// </summary>
        public static string SelectCountry {
            get {
                return ResourceManager.GetString("SelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Day.
        /// </summary>
        public static string SelectDay {
            get {
                return ResourceManager.GetString("SelectDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select.
        /// </summary>
        public static string SelectLabel {
            get {
                return ResourceManager.GetString("SelectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Month.
        /// </summary>
        public static string SelectMonth {
            get {
                return ResourceManager.GetString("SelectMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Year.
        /// </summary>
        public static string SelectYear {
            get {
                return ResourceManager.GetString("SelectYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your top skills: two strong and one weak.
        /// </summary>
        public static string softskillmessage {
            get {
                return ResourceManager.GetString("softskillmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaking.
        /// </summary>
        public static string Speaking {
            get {
                return ResourceManager.GetString("Speaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialization.
        /// </summary>
        public static string Specilization {
            get {
                return ResourceManager.GetString("Specilization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date Melade/Shamse.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Form.
        /// </summary>
        public static string SubmitApplicationForm {
            get {
                return ResourceManager.GetString("SubmitApplicationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I hereby certify that the above information is correct and correct to the best of my knowledge; I understand that any willful misstatement described herein may lead to my disqualification or dismissal, if engaged..
        /// </summary>
        public static string SubmitConfirm {
            get {
                return ResourceManager.GetString("SubmitConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Date.
        /// </summary>
        public static string SubmitDate {
            get {
                return ResourceManager.GetString("SubmitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request was successfully executed.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for applying for your favorite position in DABS, we hereby inform you that the information you provided in the application form is successfully transferred to the HR Department of DABS. &lt;br&gt;Our team will process your application and will contact you if you shortlisted.&lt;br&gt; For more information you can contact us on (02056565656565) number..
        /// </summary>
        public static string SuccessMessage {
            get {
                return ResourceManager.GetString("SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your application is received, DABS will notify you regarding further process. Please keep patience!.
        /// </summary>
        public static string SuccessNote {
            get {
                return ResourceManager.GetString("SuccessNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; Conditions.
        /// </summary>
        public static string Terms {
            get {
                return ResourceManager.GetString("Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University.
        /// </summary>
        public static string University {
            get {
                return ResourceManager.GetString("University", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country of Study.
        /// </summary>
        public static string UniversityCountry {
            get {
                return ResourceManager.GetString("UniversityCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Documents.
        /// </summary>
        public static string uploadDoc {
            get {
                return ResourceManager.GetString("uploadDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string USERName {
            get {
                return ResourceManager.GetString("USERName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VacancyNumber.
        /// </summary>
        public static string VacancyNumber {
            get {
                return ResourceManager.GetString("VacancyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Good.
        /// </summary>
        public static string vgood {
            get {
                return ResourceManager.GetString("vgood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Message (One minutes).
        /// </summary>
        public static string videomessage {
            get {
                return ResourceManager.GetString("videomessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VOLUNTEERING.
        /// </summary>
        public static string VOLUNTEERING {
            get {
                return ResourceManager.GetString("VOLUNTEERING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weak.
        /// </summary>
        public static string Weak {
            get {
                return ResourceManager.GetString("Weak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where do you live?.
        /// </summary>
        public static string Wheredoyoulive {
            get {
                return ResourceManager.GetString("Wheredoyoulive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application with video message will be prioritized..
        /// </summary>
        public static string withVideoMessage {
            get {
                return ResourceManager.GetString("withVideoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing.
        /// </summary>
        public static string Writiting {
            get {
                return ResourceManager.GetString("Writiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect image format please select correct format.
        /// </summary>
        public static string WrongFormat {
            get {
                return ResourceManager.GetString("WrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Year.
        /// </summary>
        public static string YearReqMessage {
            get {
                return ResourceManager.GetString("YearReqMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 Years.
        /// </summary>
        public static string Yesrs5 {
            get {
                return ResourceManager.GetString("Yesrs5", resourceCulture);
            }
        }
    }
}
